// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace GoucherDiningAppPOC1
{

    internal class DiningHall
    {

        [JsonProperty("Name")]
        public string Name { get; set; }
    }

}
